name: Publish Metadata to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     pages: write
     pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install markdown pyaml pillow requests opencv-python

      - name: Extract Metadata
        run: |
          mkdir -p output
          python .github/extract_metadata.py "https://gtif-austria.github.io/public-narratives/"
          cp *.md output
          touch output/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: ./output
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
